server: 
  port: 3001
  
db:
  type: 'postgres'
  port: 5432
  database: 'test_db'
  host: '127.0.0.1'
  username: 'postgres'
  password: 'postgres'
  synchronize: true

jwt:
  expiresIn: 3600
  secret: 'Secret1234'